services:
  frontend:
    profiles:
      - do_not_run
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:5173
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules/
    restart: always
    networks:
      - webserver-net
    environment:
      - BACKEND_API=http://backend:80
    depends_on:
      - backend
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules/
    restart: always
    networks:
      - webserver-net
      - databases-net
    environment:
      - MONGO_URL=mongodb://mongo:27017/velocurien
      - NEO4J_URL=bolt://neo4j:7687
    depends_on:
      - mongo
      - neo4j

  mongo:
    restart: always
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    volumes:
      - mongo_dbdata:/data/db
    networks:
      - databases-net
    expose:
      - 27017
    ports:
      - 27017:27017

  neo4j:
    restart: always
    image: neo4j:5.12.0-community-ubi8
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_dbdata:/data
    environment:
      - NEO4J_AUTH=neo4j/Cpz63Jwj8w5bDD
    networks:
      - databases-net
    expose:
      - 7474
      - 7687

  stagingservice:
    profiles:
      - staging
    build:
      context: ./staging/data_import_service
      dockerfile: Dockerfile
    volumes:
      - ./staging/data_import_service:/app
      - ./staging/raw_data/:/app/raw_data/
      - staging_py_venv:/app/venv
    restart: on-failure
    networks:
      - databases-net
    environment:
      - MONGO_STAGING_HOST=stagingdb
      - MONGO_STAGING_PORT=27017
      - MONGO_STAGING_DB=velocurien_staging
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PWD=Cpz63Jwj8w5bDD
    depends_on:
      - stagingdb
      - mongo
      - neo4j

  stagingdb:
    profiles:
      - staging
    restart: always
    ports:
      - 27018:27017
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    volumes:
      - staging_dbdata:/data/db
    networks:
      - databases-net
    expose:
      - 27017

networks:
  webserver-net:
  databases-net:

volumes:
  mongo_dbdata:
  neo4j_dbdata:
  frontend_node_modules:
  backend_node_modules:
  staging_py_venv:
  staging_dbdata:
